### ISSUE TITLE
Getting Error :: ImportError: No module named requests

### ISSUE THREAD

**Issue by titus-shoats** [swisskyrepo/Wordpresscan#1]
Hello im currently using this repo on my centos 6.7 , using the following command::
python main.py -u "http://teststite.com" --update --aggressive
and Im getting the following error:

 `python main.py -u "http://testsite.com" --update --aggressive
Traceback (most recent call last):
  File "main.py", line 3, in <module>
    import requests
ImportError: No module named requests`

Can you please let me me know whats going on with this error? Thanks

**Comment by swisskyrepo** [comment]
Hello, you need to install 'requests' (https://pypi.python.org/pypi/requests)
I added the install command line in the read me
You might also need the tornado dependencies  :smile: 

Btw the "--aggressive" option is still in dev

**Comment by ghost** [comment]
I had the same issue even after installing 'requests'.

```
Collecting request
  Downloading https://files.pythonhosted.org/packages/b8/13/b88a65f14470f3e17d72a1a930f173b36717c211685dbbadfc2e5ba21303/request-1.0.2.tar.gz
Collecting get (from request)
  Downloading https://files.pythonhosted.org/packages/dc/bd/264e65844b66e2b5fa829f3f6c526056ee14a0508fb6b454e0af4105a21c/get-1.0.3.tar.gz
Collecting post (from request)
  Downloading https://files.pythonhosted.org/packages/7f/ea/ddf22395dcee7a45b7ab7564a087725cafc778f421268814cd8a5ec9ffdf/post-1.0.2.tar.gz
Requirement already satisfied: setuptools in /usr/local/lib/python3.5/dist-packages (from request) (40.0.0)
Collecting query_string (from get->request)
  Downloading https://files.pythonhosted.org/packages/be/2d/719132c49c715743afff3781e04489cd21189914a563b56837f891fd02ac/query_string-1.0.2.tar.gz
Collecting public (from query_string->get->request)
  Downloading https://files.pythonhosted.org/packages/e8/d6/297dc43e6f84fea8f92ba3fdba0c0028a4ffd122fc05ce96ee6ab0cc59f8/public-1.0.3.tar.gz
Installing collected packages: public, query-string, get, post, request
  Running setup.py install for public ... done
  Running setup.py install for query-string ... done
  Running setup.py install for get ... done
  Running setup.py install for post ... done
  Running setup.py install for request ... done
Successfully installed get-1.0.3 post-1.0.2 public-1.0.3 query-string-1.0.2 request-1.0.2
```
__________________________________________________________________________

Then is tried again and received, 

```
Traceback (most recent call last):
  File "wordpresscan.py", line 3, in <module>
    import requests
ImportError: No module named requests
```

I am new to Python and eager to learn. Any direction would be appreciated.

**Comment by swisskyrepo** [comment]
"Collecting request"
"ImportError: No module named requests"

You want the "requests" package not "request"
