### ISSUE TITLE
url schema detection

### ISSUE THREAD

**Issue by d4op** [swisskyrepo/Wordpresscan#11]
please add a url schema detection

like -u xxxx.com
so it detects if http:// or https:// missing and follow redirects to the right url.

**Comment by lianfeng30** [comment]
Traceback (most recent call last):
  File "main.py", line 39, in <module>
    requests.packages.urllib3.disable_warnings(InsecureRequestWarning)
NameError: name 'InsecureRequestWarning' is not defined

**Comment by swisskyrepo** [comment]
This has been added to the latest version of Wordprescan, let me know if the behavior matches your expectations ;) https://github.com/swisskyrepo/Wordpresscan/commit/e78cfda969c3b2a647c77e4b1f854cbd73cb99f8
```
$ python main.py -u example.fr                                                                                                                                                                     
[+] URL: http://example.fr
[i] The remote host tried to redirect to: https://www.example.fr/
[?] Do you want to follow the redirection ? [Y]es [N]o, 
```

I also corrected the InsecureRequestWarning ;)
