### ISSUE TITLE
ERROR : "[!] Not a WordPress !"

### ISSUE THREAD

**Issue by 3jgvc** [swisskyrepo/Wordpresscan#18]
Hello, 

The script does not detect WordPress on my site.
I have ordered: 
cd Wordpresscan
python main.py -u "http://mywebsite.com" --update --random-agent

**Comment by swisskyrepo** [comment]
Hi, 
Can you provide a link to the website or at least the Wordpress version and the tree of /var/www/html ? 
By the way do you have "wp-"something in the content of the main page ?

thank you

**Comment by 3jgvc** [comment]
Hello,

Here is the website link: http://visioland.fr/
The WordPress version is WordPress 4.8.2

Cordially,

**Comment by 3jgvc** [comment]
Yet I run it well, here is a screenshot:
https://i.gyazo.com/39a1760ac6cd33fdaf45ea119a03fc03.png

**Comment by 3jgvc** [comment]
Problem solved! Thank you for your help.
