### ISSUE TITLE
LICENSE

### ISSUE THREAD

**Issue by ethicalhack3r** [swisskyrepo/Wordpresscan#2]
Hi,

Please could you update the WPScan license that you are hosting as it shows as garbled when downloading - https://github.com/swisskyrepo/Wordpresscan/blob/master/database/LICENSE

Thanks!
Ryan

**Comment by swisskyrepo** [comment]
Sure, it's corrected in the last commit (https://github.com/swisskyrepo/Wordpresscan/commit/01c1339cab0a5b4e9e642a6477efdeda043be940)
Thank you :)
