### ISSUE TITLE
error

### ISSUE THREAD

**Issue by lianfeng30** [swisskyrepo/Wordpresscan#7]
error:

[!] WordPress version 4.8.1 identified from advanced fingerprinting
Traceback (most recent call last):
  File "main.py", line 56, in <module>
    Scan_Engine(wp, results.aggressive)
  File "/Wordpresscan/engine/scan.py", line 16, in __init__
    self.list_wp_version_vulnerabilities(wordpress, "wordpresses")
  File "/Wordpresscan/engine/scan.py", line 110, in list_wp_version_vulnerabilities
    if data[wordpress.version]["vulnerabilities"] == []:
KeyError: u'4.8.1'

thanks

**Comment by lianfeng30** [comment]
WARNING:tornado.general:SSL Error on 16 ('211.*.*.6', 443): [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:590)

**Comment by swisskyrepo** [comment]
I had the same problem recently, it disappeared after updating the database, I will patch it soon
thx

**Comment by swisskyrepo** [comment]
It should be fixed with the following commit [https://github.com/swisskyrepo/Wordpresscan/commit/fa7804573c5067310a693cd940d749d6aeac3320](fa7804573c5067310a693cd940d749d6aeac3320)
;)

**Comment by lianfeng30** [comment]
oh...  thanks
