### ISSUE TITLE
Which license?

### ISSUE THREAD

**Issue by mboelen** [swisskyrepo/Wordpresscan#9]
Hi,

What license is used for this project? We couldn't find it while reviewing your tool for our security tools section: https://linuxsecurity.expert/tools/wordpresscan/

**Comment by swisskyrepo** [comment]
I don't have any particular licence for my doing, since the project is based of the work of Wpscan I have included their licence here (https://github.com/swisskyrepo/Wordpresscan/blob/master/database/LICENSE)

**Comment by mboelen** [comment]
Thanks, will update the tool review :+1:
